import { SelectBox } from "./SelectBox";
import { Switch } from "./Switch";
import { Text } from "./Text";
import { Button } from "./Button";
import { ChipView } from "./ChipView";
import { Heading } from "./Heading";
import { Img } from "./Img";
import { Input } from "./Input";
import Select from 'react-select';
export { Button, ChipView, Heading, Img, Input, SelectBox, Switch, Text };